spring:
  datasource:
    url: jdbc:postgresql://postgres_5471/analytics
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  cloud:
    function:
      definition: CreateAnalyticsFunction;LoginAnalyticsFunction;CreateAnalyticsCustomerFunction;TicketAnalyticsFunction
    stream:
      defaultBinder: kafka
      bindings:
        CreateUserAnalytics-in-0:
          destination: createUser-analytics
          content-type: application/json
          group: Analytics-group
        LoginUserAnalytics-in-0:
          destination: loginUser-analytics
          content-type: application/json
          group: Analytics-group
        CreateCustomerAnalytics-in-0:
          destination: createCustomer-analytics
          content-type: application/json
          group: Analytics-group
        TicketAnalyticsFunction-in-0:
          destination: ticket-analytics
          content-type: application/json
          group: Analytics-group
      kafka:
        binder:
          brokers: kafka:9092
  security:
    user:
      name: prometheus
      password: prometheus
eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

