spring:
  datasource:
    url: jdbc:postgresql://postgres_5435:5432/customer
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition: emailNotification;smsNotification;pushNotification
    stream:
      defaultBinder: kafka
      bindings:
        emailNotification-out-0:
          destination: emailNotificationFunction-in-0
          content-type: application/json
          group: notification-group
        smsNotification-out-0:
          destination: smsNotificationFunction-in-0
          content-type: application/json
          group: notification-group
        pushNotification-out-0:
          destination: pushNotificationFunction-in-0
          content-type: application/json
          group: notification-group
      kafka:
        binder:
          brokers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method