spring:
  mongodb:
    uri: mongodb://root:root@mongodb:27017/customerSupportdb?authSource=admin
  redis:
    host: redis
    port: 6379
    timeout: 2000
    connect-timeout: 2000
  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        TicketAnalytics-out-0:
          destination: ticket-analytics
          content-type: application/json
          group: Analytics-group-ticket
      kafka:
        binder:
          brokers: kafka:9092
jwt:
  secret: turkcellCRMMicroservicesSecretKey123456789012345678901234567890
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Actuator and Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
