spring:
  mongodb:
    uri: mongodb://mongodb:27017/customerSupportdb

jwt:
  secret: turkcellCRMMicroservicesSecretKey123456789012345678901234567890
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8888/eureka
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
