spring:
  cloud:
    gateway:
      routes:
        - id: "auth-service"
          uri: "lb://user-service"
          predicates:
            - "Path=/api/auth/**"

        - id: "user-service"
          uri: "lb://user-service"
          predicates:
            - "Path=/api/users/**"

        - id: "customer-service"
          uri: "lb://customer-service"
          predicates:
            - Path=/customer-service/**,/api/customers/**
          filters:
            - StripPrefix=1

        - id: "contract-service"
          uri: "lb://contract-service"
          predicates:
            - "Path=/api/contracts/**"
        - id: "plan-service"
          uri: "lb://plan-service"
          predicates:
            - "Path=/api/plans/**"

        - id: "billing-service"
          uri: "lb://billing-service"
          predicates:
            - "Path=/api/billings/**"

        - id: "support-service"
          uri: "lb://support-service"
          predicates:
            - "Path=/api/support/**"

        - id: "analytics-service"
          uri: "lb://analytics-service"
          predicates:
            - "Path=/api/analytics/**"

        - id: "notification-service"
          uri: "lb://notification-service"
          predicates:
            - "Path=/api/notifications/**"
eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

resilience4j:
  circuitbreaker:
    instances:
      userCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
      customerCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
      contractCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
      planCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
      billingCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
      supportCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
      analyticsCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
      notificationCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
