spring:
  application:
    name: "user-service"
  datasource:
    url: jdbc:postgresql://localhost:5433/user
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cloud:
    function:
      definition: emailNotification;smsNotification;pushNotification;CreateUserAnalytics
    stream:
      defaultBinder: kafka
      bindings:
        emailNotification-out-0:
          destination: emailNotificationFunction-in-0
          content-type: application/json
          group: notification-group
        smsNotification-out-0:
          destination: smsNotificationFunction-in-0
          content-type: application/json
          group: notification-group
        pushNotification-out-0:
          destination: pushNotificationFunction-in-0
          content-type: application/json
          group: notification-group
        CreateUserAnalytics-out-0:
          destination: CreateUserAnalytics-in-0
          content-type: application/json
          group: Analytics-group

      kafka:
        binder:
          brokers: localhost:9092

# Encryption configuration
encryption:
  secret-key: "YAQoNmCUbYdDTnwgCh11xPQ5pSI/uZJDM+dzCBL683s=" # Replace with a properly generated key in production

# JWT Configuration
jwt:
  secret-key: very-secure-jwt-secret-key-used-for-signing-tokens-in-user-service
  expiration-ms: 86400000
  issuer: user-service
  token-prefix: "Bearer "
  header-string: Authorization

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    disable-swagger-default-url: true
